# -*- mode: python ; coding: utf-8 -*-

# https://blog.csdn.net/zm147451753/article/details/85850526
# https://blog.csdn.net/tangfreeze/article/details/112240342
# pyinstaller -D WebServer.spec

block_cipher = None


a = Analysis(['WebServer.py'],
             pathex=[],
             binaries=[],
             datas=[
                ('./runtime', './runtime'),
                ('./bin', './bin'),
                ('./config/*.json', './config'),
                ('sqlite3.db', './')
             ],
             hiddenimports=[
                'scrapy.utils.misc',
                'scrapy.spiderloader',
                'scrapy.statscollectors',
                'scrapy.logformatter',
                'scrapy.dupefilters',
                'scrapy.squeues',
                'scrapy.extensions.spiderstate',
                'scrapy.extensions.corestats',
                'scrapy.extensions.telnet',
                'scrapy.extensions.logstats',
                'scrapy.extensions.memusage',
                'scrapy.extensions.memdebug',
                'scrapy.extensions.feedexport',
                'scrapy.extensions.closespider',
                'scrapy.extensions.debug',
                'scrapy.extensions.httpcache',
                'scrapy.extensions.statsmailer',
                'scrapy.extensions.throttle',
                'scrapy.core.scheduler',
                'scrapy.core.engine',
                'scrapy.core.scraper',
                'scrapy.core.spidermw',
                'scrapy.core.downloader',
                'scrapy.downloadermiddlewares.stats',
                'scrapy.downloadermiddlewares.httpcache',
                'scrapy.downloadermiddlewares.cookies',
                'scrapy.downloadermiddlewares.useragent',
                'scrapy.downloadermiddlewares.httpproxy',
                'scrapy.downloadermiddlewares.ajaxcrawl',
                'scrapy.downloadermiddlewares.decompression',
                'scrapy.downloadermiddlewares.defaultheaders',
                'scrapy.downloadermiddlewares.downloadtimeout',
                'scrapy.downloadermiddlewares.httpauth',
                'scrapy.downloadermiddlewares.httpcompression',
                'scrapy.downloadermiddlewares.redirect',
                'scrapy.downloadermiddlewares.retry',
                'scrapy.downloadermiddlewares.robotstxt',
                'scrapy.spidermiddlewares.depth',
                'scrapy.spidermiddlewares.httperror',
                'scrapy.spidermiddlewares.offsite',
                'scrapy.spidermiddlewares.referer',
                'scrapy.spidermiddlewares.urllength',
                'scrapy.pipelines',
                'scrapy.core.downloader.handlers.http',
                'scrapy.core.downloader.contextfactory',
                'pyscrapy.settings',
                'pyscrapy.middlewares',
                'pyscrapy.pipelines',
                'scrapy.pipelines.images',
                'openpyxl'
             ],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts, 
          [],
          exclude_binaries=True,
          name='WebServer',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None, icon='santic.ico')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas, 
               strip=False,
               upx=True,
               upx_exclude=[],
               name='WebServer')
